name: Fetch Cat Image

on: [push]

jobs:
  fetch_cat_image:
    runs-on: ubuntu-latest
    name: Fetch Cat Image Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Fetch Cat Image
        run: python fetch_cat_image.py
        env:
          CAT_API_KEY: ${{ secrets.CAT_API_KEY }}
