name: Python Hello World Workflow

on: [push]

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    name: Run Python Script
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        echo "No dependencies to install"
    - name: Run the script
      run: python hello_world.py
